---
DOMAIN_NAME: apv
LOCAL_IP: 10.10.10.10


ansible_roles_list:
- geerlingguy.adminer
- geerlingguy.composer
- geerlingguy.firewall
- geerlingguy.git
- geerlingguy.mysql
- geerlingguy.nginx
- geerlingguy.nodejs
- geerlingguy.php
- geerlingguy.php-mysql
